### ISSUE TITLE
Just a thanks!

### ISSUE THREAD

**Issue by nackjicholson** [abevoelker/haskellbook-solutions#1]
Hey wanted to say thanks for putting these on github, through the first eight chapters they've been a big help to me.

I have my own version here https://github.com/nackjicholson/haskellbook-solutions and now that I'm passing your stopping point and moving on to chapter9 I figured I'd let you know these will be there for ya when you get back to it :)

Any help or suggestions would be awesome too. Thanks again!

**Comment by abevoelker** [comment]
Woah I never expected anyone to read my solutions, so I'm very glad they were helpful!

Thanks for sharing your solutions for later chapters; I needed a kick in the pants to get back to reading the book, and now I have that and a reference if I need it. Thank you!
